
* Goal
  Use my webcamera and microphone under a Windows guest in virtualbox on a Linux host.

* TLDR

  - Install Virtualbox
  - Install Install virtualbox extensions
  - start the VM
  - add the webcam

* Background

  The class I am a co-instructor on is an online course. Several times
  a week we use Adobe Connect to interact with the students
  directly. Additionally, we use Microsoft's Office Mix to add video
  and sound to Powerpoint presentations. My workstation is a Linux
  machine. Unfortunately, Adobe Connect requires a current version of
  Flash, among other things. Getting flash to work reliably on Linux
  has proven slightly problematic in the past. Additionally, Office
  Mix only works on Windows.

  As my workstation is rather beefy, it should support running
  everything under a Windows VM. Once Virtualbox is installed, a
  Windows VM initialized and the VBox Guest additions installed, it
  turns out that webcam on the host is not detected by the guest.

* Solution

  It turns out that vanilla VirtualBox does not detect the EHCI usb
  controller. Apparently VirtualBox, starting with 4.0, is [[https://www.virtualbox.org/manual/ch01.html#intro-installing][split]] into
  an open source version component and extensions released as blobs
  with Oracle-related licensing. In order to get certain components
  working, such as the webcam, I need to install the appropriate
  extension pack.

  The extension packs are available from the [[https://www.virtualbox.org/wiki/Downloads][VirtualBox Download Page]].
  Make sure to get the version of the extpack matching the installed
  virtualbox version.

  #+BEGIN_EXAMPLE
  $ wget http://download.virtualbox.org/virtualbox/4.3.26/Oracle_VM_VirtualBox_Extension_Pack-4.3.26-98988.vbox-extpack
  #+END_EXAMPLE

  Install the pack by running:
  #+BEGIN_EXAMPLE
  $ vboxmanage extpack install Oracle_VM_VirtualBox_Extension_Pack-4.3.26-98988.vbox-extpack
  #+END_EXAMPLE

  I then started the virtual machine and connected the webcam:
  #+BEGIN_EXAMPLE
  $ vboxmanage controlvm "Windows 8" webcam attach
  #+END_EXAMPLE

  The webcam was immediately detected.
